# Flutter engine + plugin entry points
-keep class io.flutter.app.** { *; }
-keep class io.flutter.plugin.** { *; }
-keep class io.flutter.util.** { *; }
-keep class io.flutter.view.** { *; }
-keep class io.flutter.** { *; }
-keep class io.flutter.plugins.** { *; }

# Google Play Core — referenced reflectively by the deferred-components shim
# even when the app does not use dynamic delivery. Without these rules R8
# strips the classes and the build fails with "missing class" errors.
-keep class com.google.android.play.core.** { *; }
-dontwarn com.google.android.play.core.**

# Web3Auth (social sign-in). web3auth_flutter 7.0.0 ships these as
# android/consumer_rules.pro but its build.gradle does not declare
# consumerProguardFiles, so they are never applied — without them R8 strips
# the login SDK from release builds, a failure invisible to analyze/tests.
# Vendor rules inlined (deduplicated); re-check on SDK upgrades.
-keep class com.web3auth.** { *; }
-keep class com.google.gson.** { *; }
-keepclassmembers class * {
    @com.google.gson.annotations.SerializedName <fields>;
}
-keepattributes Signature, InnerClasses, EnclosingMethod, *Annotation*, SourceFile, LineNumberTable
-keep class kotlin.Metadata { *; }
-keepclassmembers class ** {
    @kotlin.Metadata *;
}
-keep class kotlinx.coroutines.** { *; }
-dontwarn kotlinx.coroutines.**

# The Web3Auth Android SDK's transitive deps (jackson-databind, bouncycastle,
# okhttp) reference JVM-only optional classes — java.beans reflection, LDAP
# CRL fetching, conscrypt/bc-jsse/openjsse TLS providers — that never execute
# on Android. R8 treats the dangling references as errors without these.
# Generated by R8 (build/app/outputs/mapping/release/missing_rules.txt).
-dontwarn java.beans.ConstructorProperties
-dontwarn java.beans.Transient
-dontwarn javax.naming.NamingEnumeration
-dontwarn javax.naming.NamingException
-dontwarn javax.naming.directory.Attribute
-dontwarn javax.naming.directory.Attributes
-dontwarn javax.naming.directory.DirContext
-dontwarn javax.naming.directory.InitialDirContext
-dontwarn javax.naming.directory.SearchControls
-dontwarn javax.naming.directory.SearchResult
-dontwarn org.bouncycastle.jsse.BCSSLParameters
-dontwarn org.bouncycastle.jsse.BCSSLSocket
-dontwarn org.bouncycastle.jsse.provider.BouncyCastleJsseProvider
-dontwarn org.conscrypt.Conscrypt$Version
-dontwarn org.conscrypt.Conscrypt
-dontwarn org.conscrypt.ConscryptHostnameVerifier
-dontwarn org.openjsse.javax.net.ssl.SSLParameters
-dontwarn org.openjsse.javax.net.ssl.SSLSocket
-dontwarn org.openjsse.net.ssl.OpenJSSE
-dontwarn org.slf4j.impl.StaticLoggerBinder
